name: main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build seqs server
      run: cd cmd/seqs && go build
    - name: Build submit server
      run: cd cmd/submit && go build
    - name: Build stats server
      run: cd cmd/stats && go build
    - name: Test
      run: go test -v ./...
    - name: Build Docker image
      run: docker build . -t loda-api
